name: Run Python UnitTests on Push

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run unit tests (tests inside modules)
        run: |
          python3 -m unittest -v circle.py
          python3 -m unittest -v rectangle.py
          python3 -m unittest -v square.py
          python3 -m unittest -v triangle.py